name: Android CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Development build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'

      # Manually install latest build tools (takes up to two weeks to update in action images)
      - name: Install latest build tools
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "build-tools;33.0.0" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;25.1.8937393" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Build with Gradle
        run: ./gradlew assembleRelease --stacktrace

      # - name: Upload APK
      #   uses: actions/upload-artifact@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     name: AdAway-dev
      #     path: app/build/outputs/apk/release/app-release-unsigned.apk
      
      - name: Update dependency graph
        uses: mikepenz/gradle-dependency-submission@v0.0.5
        with:
          gradle-dependency-path: "app/build.gradle"
          gradle-build-module: ":app"
          gradle-build-configuration: "releaseCompileClasspath"
